name: yango_expert
description: La comptabilite dans la poche - App VTC Dakar
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.3.4
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  fl_chart: ^0.67.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  uuid: ^4.3.3
  connectivity_plus: ^6.0.3
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  path_provider: ^2.1.3
  url_launcher: ^6.2.5
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.20
  flutter_local_notifications: ^17.0.0
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
